config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get 'models' => 'welcome#models'
  get 'model' => 'welcome#model'
  post 'search' => 'welcome#search'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @brands = Gsmarena.brands
  end

  def models
    render json: Gsmarena.models(params[:uri]).sort_by { |m| m["name"] }
  end

  def model
    render json: Gsmarena.model(params[:uri])
  end

  def search
    render json: Gsmarena.find(params[:value])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}
    %title PhoneGrabber
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield

app/views/welcome/index.haml
.row
  .col-sm-6
    %h4 Select brand
    %select#j-brands.form-control
      %option
      - @brands.each do |brand|
        %option{value:brand[:uri]}=brand[:name]


    #j-select_model_wrrapper.hide
      %h4 Select model
      %select#j-models.form-control
        %option

    #j-model_info_wrrapper.hide
      %h4 Model info
      #j-results.select-results

  .col-sm-6
    %h4 Search
    =form_for :search, url: search_path, html: {class:'form-inline', id:'j-search_form'}, remote:true do |f|
      .form-group
        =f.text_field :value, name: "value", class:"form-control"
      .form-group
        =f.submit "Search", class: "btn btn-default", id: "j_search_subimt"
    #j-search_results